// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/upload/upload.proto

package upload

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_api_proto_upload_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_upload_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_upload_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_api_proto_upload_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_upload_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_upload_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

var File_api_proto_upload_upload_proto protoreflect.FileDescriptor

const file_api_proto_upload_upload_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/upload/upload.proto\x12\x06upload\"0\n" +
	"\x11UploadFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"1\n" +
	"\x12UploadFileResponse\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath2T\n" +
	"\rUploadService\x12C\n" +
	"\n" +
	"UploadFile\x12\x19.upload.UploadFileRequest\x1a\x1a.upload.UploadFileResponseB$Z\"megareds/mediahub/api/proto/uploadb\x06proto3"

var (
	file_api_proto_upload_upload_proto_rawDescOnce sync.Once
	file_api_proto_upload_upload_proto_rawDescData []byte
)

func file_api_proto_upload_upload_proto_rawDescGZIP() []byte {
	file_api_proto_upload_upload_proto_rawDescOnce.Do(func() {
		file_api_proto_upload_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_upload_upload_proto_rawDesc), len(file_api_proto_upload_upload_proto_rawDesc)))
	})
	return file_api_proto_upload_upload_proto_rawDescData
}

var file_api_proto_upload_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_upload_upload_proto_goTypes = []any{
	(*UploadFileRequest)(nil),  // 0: upload.UploadFileRequest
	(*UploadFileResponse)(nil), // 1: upload.UploadFileResponse
}
var file_api_proto_upload_upload_proto_depIdxs = []int32{
	0, // 0: upload.UploadService.UploadFile:input_type -> upload.UploadFileRequest
	1, // 1: upload.UploadService.UploadFile:output_type -> upload.UploadFileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_upload_upload_proto_init() }
func file_api_proto_upload_upload_proto_init() {
	if File_api_proto_upload_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_upload_upload_proto_rawDesc), len(file_api_proto_upload_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_upload_upload_proto_goTypes,
		DependencyIndexes: file_api_proto_upload_upload_proto_depIdxs,
		MessageInfos:      file_api_proto_upload_upload_proto_msgTypes,
	}.Build()
	File_api_proto_upload_upload_proto = out.File
	file_api_proto_upload_upload_proto_goTypes = nil
	file_api_proto_upload_upload_proto_depIdxs = nil
}
