// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityStatus int32

const (
	EntityStatus_ENTITY_STATUS_UNKNOWN  EntityStatus = 0
	EntityStatus_ENTITY_STATUS_ACTIVE   EntityStatus = 1
	EntityStatus_ENTITY_STATUS_INACTIVE EntityStatus = 2
	EntityStatus_ENTITY_STATUS_PENDING  EntityStatus = 3
	EntityStatus_ENTITY_STATUS_DELETED  EntityStatus = 4
)

// Enum value maps for EntityStatus.
var (
	EntityStatus_name = map[int32]string{
		0: "ENTITY_STATUS_UNKNOWN",
		1: "ENTITY_STATUS_ACTIVE",
		2: "ENTITY_STATUS_INACTIVE",
		3: "ENTITY_STATUS_PENDING",
		4: "ENTITY_STATUS_DELETED",
	}
	EntityStatus_value = map[string]int32{
		"ENTITY_STATUS_UNKNOWN":  0,
		"ENTITY_STATUS_ACTIVE":   1,
		"ENTITY_STATUS_INACTIVE": 2,
		"ENTITY_STATUS_PENDING":  3,
		"ENTITY_STATUS_DELETED":  4,
	}
)

func (x EntityStatus) Enum() *EntityStatus {
	p := new(EntityStatus)
	*p = x
	return p
}

func (x EntityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_common_proto_enumTypes[0].Descriptor()
}

func (EntityStatus) Type() protoreflect.EnumType {
	return &file_api_proto_common_common_proto_enumTypes[0]
}

func (x EntityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityStatus.Descriptor instead.
func (EntityStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_PRIORITY_UNKNOWN  Priority = 0
	Priority_PRIORITY_LOW      Priority = 1
	Priority_PRIORITY_MEDIUM   Priority = 2
	Priority_PRIORITY_HIGH     Priority = 3
	Priority_PRIORITY_CRITICAL Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNKNOWN",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNKNOWN":  0,
		"PRIORITY_LOW":      1,
		"PRIORITY_MEDIUM":   2,
		"PRIORITY_HIGH":     3,
		"PRIORITY_CRITICAL": 4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_common_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_api_proto_common_common_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{1}
}

type ProcessingStatus int32

const (
	ProcessingStatus_PROCESSING_STATUS_UNKNOWN    ProcessingStatus = 0
	ProcessingStatus_PROCESSING_STATUS_QUEUED     ProcessingStatus = 1
	ProcessingStatus_PROCESSING_STATUS_PROCESSING ProcessingStatus = 2
	ProcessingStatus_PROCESSING_STATUS_COMPLETED  ProcessingStatus = 3
	ProcessingStatus_PROCESSING_STATUS_FAILED     ProcessingStatus = 4
	ProcessingStatus_PROCESSING_STATUS_CANCELLED  ProcessingStatus = 5
)

// Enum value maps for ProcessingStatus.
var (
	ProcessingStatus_name = map[int32]string{
		0: "PROCESSING_STATUS_UNKNOWN",
		1: "PROCESSING_STATUS_QUEUED",
		2: "PROCESSING_STATUS_PROCESSING",
		3: "PROCESSING_STATUS_COMPLETED",
		4: "PROCESSING_STATUS_FAILED",
		5: "PROCESSING_STATUS_CANCELLED",
	}
	ProcessingStatus_value = map[string]int32{
		"PROCESSING_STATUS_UNKNOWN":    0,
		"PROCESSING_STATUS_QUEUED":     1,
		"PROCESSING_STATUS_PROCESSING": 2,
		"PROCESSING_STATUS_COMPLETED":  3,
		"PROCESSING_STATUS_FAILED":     4,
		"PROCESSING_STATUS_CANCELLED":  5,
	}
)

func (x ProcessingStatus) Enum() *ProcessingStatus {
	p := new(ProcessingStatus)
	*p = x
	return p
}

func (x ProcessingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_common_proto_enumTypes[2].Descriptor()
}

func (ProcessingStatus) Type() protoreflect.EnumType {
	return &file_api_proto_common_common_proto_enumTypes[2]
}

func (x ProcessingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingStatus.Descriptor instead.
func (ProcessingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{2}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_api_proto_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_api_proto_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetails) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_proto_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_api_proto_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Timestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamps) Reset() {
	*x = Timestamps{}
	mi := &file_api_proto_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamps) ProtoMessage() {}

func (x *Timestamps) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamps.ProtoReflect.Descriptor instead.
func (*Timestamps) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *Timestamps) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Timestamps) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Timestamps) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_api_proto_common_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{5}
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_api_proto_common_common_proto protoreflect.FileDescriptor

const file_api_proto_common_common_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/common/common.proto\x12\x06common\"P\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"\xb5\x01\n" +
	"\fErrorDetails\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\adetails\x18\x03 \x03(\v2!.common.ErrorDetails.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"D\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"i\n" +
	"\n" +
	"Timestamps\x12\x1d\n" +
	"\n" +
	"created_at\x18\x01 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\x03R\tdeletedAt\"u\n" +
	"\fFileMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash*\x95\x01\n" +
	"\fEntityStatus\x12\x19\n" +
	"\x15ENTITY_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ENTITY_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16ENTITY_STATUS_INACTIVE\x10\x02\x12\x19\n" +
	"\x15ENTITY_STATUS_PENDING\x10\x03\x12\x19\n" +
	"\x15ENTITY_STATUS_DELETED\x10\x04*q\n" +
	"\bPriority\x12\x14\n" +
	"\x10PRIORITY_UNKNOWN\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x04*\xd1\x01\n" +
	"\x10ProcessingStatus\x12\x1d\n" +
	"\x19PROCESSING_STATUS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18PROCESSING_STATUS_QUEUED\x10\x01\x12 \n" +
	"\x1cPROCESSING_STATUS_PROCESSING\x10\x02\x12\x1f\n" +
	"\x1bPROCESSING_STATUS_COMPLETED\x10\x03\x12\x1c\n" +
	"\x18PROCESSING_STATUS_FAILED\x10\x04\x12\x1f\n" +
	"\x1bPROCESSING_STATUS_CANCELLED\x10\x05B$Z\"megareds/mediahub/api/proto/commonb\x06proto3"

var (
	file_api_proto_common_common_proto_rawDescOnce sync.Once
	file_api_proto_common_common_proto_rawDescData []byte
)

func file_api_proto_common_common_proto_rawDescGZIP() []byte {
	file_api_proto_common_common_proto_rawDescOnce.Do(func() {
		file_api_proto_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_common_common_proto_rawDesc), len(file_api_proto_common_common_proto_rawDesc)))
	})
	return file_api_proto_common_common_proto_rawDescData
}

var file_api_proto_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_common_common_proto_goTypes = []any{
	(EntityStatus)(0),         // 0: common.EntityStatus
	(Priority)(0),             // 1: common.Priority
	(ProcessingStatus)(0),     // 2: common.ProcessingStatus
	(*Status)(nil),            // 3: common.Status
	(*ErrorDetails)(nil),      // 4: common.ErrorDetails
	(*Pagination)(nil),        // 5: common.Pagination
	(*PaginationRequest)(nil), // 6: common.PaginationRequest
	(*Timestamps)(nil),        // 7: common.Timestamps
	(*FileMetadata)(nil),      // 8: common.FileMetadata
	nil,                       // 9: common.ErrorDetails.DetailsEntry
}
var file_api_proto_common_common_proto_depIdxs = []int32{
	9, // 0: common.ErrorDetails.details:type_name -> common.ErrorDetails.DetailsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_common_common_proto_init() }
func file_api_proto_common_common_proto_init() {
	if File_api_proto_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_common_common_proto_rawDesc), len(file_api_proto_common_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_common_proto_goTypes,
		DependencyIndexes: file_api_proto_common_common_proto_depIdxs,
		EnumInfos:         file_api_proto_common_common_proto_enumTypes,
		MessageInfos:      file_api_proto_common_common_proto_msgTypes,
	}.Build()
	File_api_proto_common_common_proto = out.File
	file_api_proto_common_common_proto_goTypes = nil
	file_api_proto_common_common_proto_depIdxs = nil
}
